Set up a "Hello world" project as one app with Webpack
Nasirkhan294/hello-rails-react pull request #1
Opened 2023-09-18 11:20 UTC by Nasirkhan294

### In this milestone I: 

- [ ] Created a new Rails app called 'hello-rails-react'
- [ ] Created a babel.config.js in the root folder of your project as described
- [ ] Updated webpack.config.js to include the babel-loader as described
- [ ] Created a table for storing the messages for 5 different greetings
- [ ] Created an API endpoint that selects a random greeting
- [ ] Created a static view that will be the root of your app.
- [ ] Created the App component with react-router and rendered it in a static view.
- [ ] Created the Greeting component that will display a greeting.
- [ ] Created a store, an action, and a reducer that will connect to the API endpoint to get the random greeting.
- [ ] Displayed the random greeting in the Greeting component.

2023-09-18 20:15 UTC, danmainah requested changes
Hi @Nasirkhan294 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Created a new Rails app called 'hello-rails-react` using the command the command rails new -j webpack my_new_rails_app
✔️  Added an API endpoint for returning a random greeting.
✔️  Added an app and greeting components and ensured the components use the data from the API endpoint to display a random greeting.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-18 20:15 UTC, danmainah commented on app/javascript/components/Greeting.js
> +  console.log(greeting);
- [ ] @Nasirkhan294 Great work on your app, however using console.log statement in your codebase is not a good practice, as it might expose sensitive data to unwanted viewers.
- [ ] @Nasirkhan294 I also noted your app is missing the App.js component that is supposed to handle routing in your app using react-router.
![image](https://github.com/Nasirkhan294/hello-rails-react/assets/61408860/19328dd3-036d-4885-abe2-8484081d927f)

2023-09-19 05:33 UTC, Nasirkhan294 commented on app/javascript/components/Greeting.js
> +  console.log(greeting);
Hi @danmainah, Thanks for highlighting the issues, I will fix them.

2023-09-19 06:23 UTC, roshan-bajgain approved these changes
Hi @Nasirkhan294, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Good job on requesting the changes ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-19 06:49 UTC, merged